[package]
name = "dhai-chain"
version = "0.1.0"
edition = "2021"

[dependencies]
sha2 = "0.10.8"
time = { version = "0.3", features = ["formatting", "macros"] }
thiserror = "1.0"

[dev-dependencies]
test-case = "3.3"
